#!/usr/bin/env bash

uptime=$(uptime -p | sed -e "s/up //g")

shutdown="⏻ Shutdown"
reboot=" Reboot"
logout="󰍃 Logout"
lock=" Lock"

option=$(echo -e "$shutdown\n$reboot\n$logout\n$lock"| rofi -dmenu -theme-str "window {width: 550px;}" -i -p "Select Power Mode" -mesg "Uptime: $uptime" -l 4)

case $option in
  "$shutdown")
    systemctl poweroff
    ;;
  "$reboot")
    systemctl reboot
    ;;
  "$logout")
    hyprctl dispatch exit
    ;;
  "$lock")
    hyprlock
    ;;
  *)
    exit 0
esac
