#!/usr/bin/env bash

# This script is a hyprshot tool for screenshotting.
# Made for my little brother.

# Path for storing screenshots.
folder_path="$HOME/Pictures/Screenshots"

# Selecting the screenshot mode. -l --> number of lines
mode=$(echo "Entire Monitor|Certain Window|Selected Region" | rofi -sep "|" -dmenu -l 3 -p "Select Screenshot Mode")
# Exiting if the user does not select a mode.
if [[ $mode == '' ]];then
  exit 0
fi

# Save to clipboard or disk
clipboard=$(echo "Copy to clipboard|Save to disk" | rofi -sep "|" -dmenu -l 2 -p "Save to clipboard or disk")

if [[ $mode == "Entire Monitor" ]]; then
  if [[ $clipboard == "Copy to clipboard" ]]; then
    hyprshot --mode output --clipboard-only
    exit 0
  else
    hyprshot --mode output --output-folder "$folder_path"
    exit 0
  fi
fi

if [[ $mode == "Certain Window" ]]; then
  if [[ $clipboard == "Copy to clipboard" ]]; then
    hyprshot --mode window --clipboard-only
    exit 0
  else
    hyprshot --mode window --output-folder "$folder_path"
    exit 0
  fi
fi

if [[ $mode == "Selected Region" ]]; then
  if [[ $clipboard == "Copy to clipboard" ]]; then
    hyprshot --mode region --clipboard-only
    exit 0
  else
    hyprshot --mode region --output-folder "$folder_path"
    exit 0
  fi
fi
