#!/usr/bin/env bash

utils=(Nmtui Bluetui Wiremix Btop Nvtop Yazi Clipse Disk-Usage)

util=$(echo "${utils[*]}" | rofi -theme-str "window {width: 550px;}" -dmenu -i -sep " " -p "Select which utility you want to open" -l "${#utils[*]}") # "${#utils[*]}" this gives us the length of an array

case "$util" in
  Nmtui)
    kitty --class utils -e nmtui
    ;;
  Bluetui)
    kitty --class utils -e bluetui
    ;;
  Wiremix)
    kitty --class utils -e wiremix
    ;;
  Btop)
    kitty --class utils -e btop
    ;;
  Nvtop)
    kitty --class utils -e nvtop
    ;;
  Yazi)
    kitty --class utils -e yazi
    ;;
  Clipse)
    kitty --class utils -e clipse
    ;;
  Disk-Usage)
    kitty --class utils -e dua i
    ;;
  *)
    exit 0
esac
