#!/usr/bin/env bash

dir="/home/inshaal/Wallpaper-Repository"

wallpaper=$(ls $dir | rofi -dmenu -p "Select a wallpaper")

if [[ $wallpaper == "" ]]; then
  notify-send "Error" "No wallpaper has been selected."
  exit 0
else
  hyprctl hyprpaper wallpaper "eDP-1, $dir/$wallpaper"
  wal -i "$dir/$wallpaper"
  notify-send "Wallpaper Changed" "Wallpaper has been changed to $wallpaper."
  exit 0
fi

