[pyprland]
plugins = [
  "expose",
  "scratchpads",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "60% 60%"
position = "21% 20%"
margin = 50
preserve_aspect = true

[scratchpads.spf]
animation = "fromTop"
command = "kitty --class superfile spf"
class = "superfile"
size = "60% 60%"
position = "21% 20%"
margin = 50
preserve_aspect = true

[scratchpads.btop]
animation = "fromTop"
command = "kitty --class btop btop"
class = "btop"
size = "60% 60%"
position = "21% 20%"
margin = 50
preserve_aspect = true

[scratchpads.termusic]
animation = "fromTop"
command = "kitty --class termusic termusic -c"
class = "termusic"
size = "60% 60%"
position = "21% 20%"
margin = 50
preserve_aspect = true

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class yazi yazi"
class = "yazi"
size = "60% 60%"
position = "21% 20%"
margin = 50
preserve_aspect = true
