$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, Q, killactive
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, A, exec, rofi -show window -window-format "{t}"
bind = $mainMod, T, togglefloating
bind = $mainMod, F, fullscreen, 0
bind = $mainMod Shift, F, fullscreen, 1
bind = $mainMod, B, exec, pkill waybar || waybar
bind = $mainMod, O, hyprexpo:expo, toggle
###########################
# Binding For My Programs #
###########################
bind = $mainMod, return, exec, kitty
bind = $mainMod, E, exec, nautilus
#########################
### Scripts Section. ###
#########################
bind = $mainMod, S, exec, ~/Dotfiles/hypr/scripts/screenshot
bind = $mainMod, U, exec, ~/Dotfiles/hypr/scripts/utils
bind = $mainMod, P, exec, ~/Dotfiles/hypr/scripts/powermenu
bind = $mainMod, W, exec, ~/Dotfiles/hypr/scripts/wch
