windowrule {
  name = rule for nwg-look
  float = on
  center = 1
  match:class = nwg-look
  match:title = nwg-look
}

windowrule {
  name = center local send app
  size = 1200 700
  float = on
  center = 1
  match:class = localsend
}
windowrule {
  name = center utilities
  size = 1200 700
  float = on
  center = 1
  match:class = btop|yazi|nvtop|wiremix|bluetui|nmtui|clipse
}

windowrule {
  name = center modals
  size = 1500 700
  float = on
  center = 1
  match:title = [Enter the name of file to save to|Save As].*
  match:class = [zen].*
}

windowrule {
  name = center xdg modals
  size = 1200 700
  pin = on
  float = on
  center = 1
  match:title = Select Image
  match:class = [xdg-desktop-portal-gtk]
}

windowrule {
  name = Window Rule for calculator
  float = on
  match:title = Calculator
  match:class = org.gnome.Calculator
}

windowrule {
  name = Window Rule for calculator
  size = 1145 624
  float = on
  match:title = Weather
  match:class = org.gnome.Weather
}

windowrule {
  name = Window Rule for extraction prompt
  size = 1015 586
  float = on
  center = 1
  match:title = Select Extract Destination
  match:class = org.gnome.Nautilus
}
